"""
Utilities for data management
"""
import json
import re
import os
from pathlib import Path
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash


# Data directory path
BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / 'data'
DATA_DIR.mkdir(exist_ok=True)


def sanitize_email(email: str) -> str:
    """Sanitize email for filename"""
    email = email.lower().strip()
    return re.sub(r'[^a-z0-9._-]+', '_', email)


def get_user_file_path(email: str) -> Path:
    """Get file path for user data"""
    safe = sanitize_email(email)
    return DATA_DIR / f"{safe}.json"


def get_default_years() -> list:
    """Get default years based on current year
    Only includes past year and current year. Future years should be generated by AI when needed.
    """
    current_year = datetime.now().year
    # Only include past year and current year by default
    # Future years will be generated by AI predictions when needed
    return [current_year - 1, current_year]


def load_user(email: str) -> dict:
    """Load user data from JSON file"""
    file_path = get_user_file_path(email)
    default_years = get_default_years()
    default_global = get_default_global_data()
    
    if not file_path.exists():
        # Initialize default data
        initial = {
            'years': default_years,
            'datasets': {},
            'globalData': default_global
        }
        save_user(email, initial)
        return initial
    
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
            
            # Nettoyer automatiquement les années invalides (< 2000 ou > année actuelle + 10)
            # Les années futures au-delà de 10 ans ne doivent pas être générées automatiquement
            current_year = datetime.now().year
            max_allowed_year = current_year + 10
            years = data.get('years', default_years)
            valid_years = [y for y in years if 2000 <= y <= max_allowed_year]
            invalid_years = [y for y in years if y < 2000 or y > max_allowed_year]
            
            # Supprimer les datasets des années invalides
            datasets = data.get('datasets', {})
            if invalid_years:
                for invalid_year in invalid_years:
                    year_key = str(invalid_year)
                    if year_key in datasets:
                        del datasets[year_key]
                
                # Si des années invalides ont été supprimées, sauvegarder les données nettoyées
                if invalid_years:
                    cleaned_data = {
                        'years': valid_years,
                        'datasets': datasets,
                        'globalData': data.get('globalData', default_global)
                    }
                    save_user(email, cleaned_data)
            
            return {
                'years': valid_years,
                'datasets': datasets,
                'globalData': data.get('globalData', default_global)
            }
    except (json.JSONDecodeError, IOError):
        # Return default if file is corrupted
        return {
            'years': default_years,
            'datasets': {},
            'globalData': default_global
        }


def save_user(email: str, data: dict) -> None:
    """
    Save user data to JSON file
    Note: Backup automatique peut être ajouté ici si nécessaire
    """
    file_path = get_user_file_path(email)
    try:
        # Créer le répertoire si nécessaire
        file_path.parent.mkdir(parents=True, exist_ok=True)
        
        # Écrire de manière atomique pour éviter la corruption
        temp_path = file_path.with_suffix('.json.tmp')
        with open(temp_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
            f.write('\n')
        
        # Remplacer atomiquement le fichier
        temp_path.replace(file_path)
        
        print(f"✅ Données sauvegardées pour {email} dans {file_path}")
    except Exception as e:
        print(f"❌ Erreur lors de la sauvegarde pour {email}: {e}")
        import traceback
        traceback.print_exc()
        raise


def get_default_year_data() -> dict:
    """Get default year data structure with zero targets (user must set their own budget)"""
    # Catégories par défaut avec target à 0€ - l'utilisateur doit définir son propre budget
    categories = [
        {'id': 'achats', 'name': 'Achats & Loisirs', 'target': 0},
        {'id': 'alimentation', 'name': 'Alimentation', 'target': 0}
    ]
    
    return {
        'categories': categories,
        'expenses': [],
        'subs': [],
        'annualFixedExpenses': [],
        'monthlySalary': 0,
        'variableMonthlyIncomes': None,
        'additionalMonthlyIncomes': [],
        'currentSavings': 0,
        'savingsTransactions': []
    }


def get_default_global_data() -> dict:
    """Get default global user data structure"""
    import uuid
    return {
        'bankAccounts': [
            {
                'id': str(uuid.uuid4()),
                'name': 'Compte courant',
                'balance': 0,
                'type': 'checking',
                'isShared': False,
                'sharedWith': ''
            }
        ],
        'investments': [],
        'savingsGoals': [],
        'savingsProjects': [],
        'temporaryIncomes': [],
        'sharedExpensePersons': [],
        'personTransactions': [],
        'salaryHistory': [],
        'initializationComplete': False,
        'monthlySalary': 0,
        'monthlySalaryStartDate': None,
        'lockedYears': [],
        'excludedPredictedYears': [],
        'maxPredictedYears': 3
    }
