// Catégories socio-professionnelles officielles en France (nomenclature PCS INSEE complète)
// Basée sur la nomenclature PCS 2020 de l'INSEE avec 8 groupes, 29 catégories et 311 professions
export const CSP_OPTIONS = [
  // ============================================
  // GROUPE 1 : AGRICULTEURS EXPLOITANTS
  // ============================================
  { value: 'agriculteur_exploitant', label: 'Agriculteur exploitant' },
  { value: 'agriculteur_grand_exploitant', label: 'Grand agriculteur exploitant' },
  { value: 'agriculteur_moyen_exploitant', label: 'Agriculteur exploitant moyen' },
  { value: 'agriculteur_petit_exploitant', label: 'Petit agriculteur exploitant' },
  { value: 'agriculteur_salarie', label: 'Salarié agricole' },
  { value: 'ouvrier_agricole', label: 'Ouvrier agricole' },
  { value: 'ouvrier_forestier', label: 'Ouvrier forestier' },
  { value: 'ouvrier_pecheur', label: 'Ouvrier pêcheur' },
  { value: 'ouvrier_aquaculteur', label: 'Ouvrier aquaculteur' },
  
  // ============================================
  // GROUPE 2 : ARTISANS, COMMERÇANTS, CHEFS D'ENTREPRISE
  // ============================================
  { value: 'artisan', label: 'Artisan' },
  { value: 'artisan_batiment', label: 'Artisan du bâtiment' },
  { value: 'artisan_mecanique', label: 'Artisan de la mécanique' },
  { value: 'artisan_alimentaire', label: 'Artisan de l\'alimentation' },
  { value: 'artisan_textile', label: 'Artisan du textile, cuir' },
  { value: 'artisan_autre', label: 'Autre artisan' },
  { value: 'commercant', label: 'Commerçant' },
  { value: 'commercant_detail', label: 'Commerçant de détail' },
  { value: 'commercant_gros', label: 'Commerçant de gros' },
  { value: 'commercant_automobile', label: 'Commerçant automobile' },
  { value: 'chef_entreprise_10', label: 'Chef d\'entreprise de 10 salariés ou plus' },
  { value: 'chef_entreprise_moins_10', label: 'Chef d\'entreprise de moins de 10 salariés' },
  { value: 'chef_entreprise_industrie', label: 'Chef d\'entreprise de l\'industrie' },
  { value: 'chef_entreprise_batiment', label: 'Chef d\'entreprise du bâtiment' },
  { value: 'chef_entreprise_commerce', label: 'Chef d\'entreprise du commerce' },
  { value: 'chef_entreprise_service', label: 'Chef d\'entreprise de services' },
  
  // ============================================
  // GROUPE 3 : CADRES ET PROFESSIONS INTELLECTUELLES SUPÉRIEURES
  // ============================================
  // Professions libérales
  { value: 'profession_liberale', label: 'Profession libérale' },
  { value: 'medecin', label: 'Médecin' },
  { value: 'medecin_generaliste', label: 'Médecin généraliste' },
  { value: 'medecin_specialiste', label: 'Médecin spécialiste' },
  { value: 'chirurgien', label: 'Chirurgien' },
  { value: 'pharmacien', label: 'Pharmacien' },
  { value: 'pharmacien_officine', label: 'Pharmacien d\'officine' },
  { value: 'pharmacien_industrie', label: 'Pharmacien industrie' },
  { value: 'veterinaire', label: 'Vétérinaire' },
  { value: 'avocat', label: 'Avocat' },
  { value: 'notaire', label: 'Notaire' },
  { value: 'huissier', label: 'Huissier de justice' },
  { value: 'expert_comptable', label: 'Expert-comptable' },
  { value: 'architecte', label: 'Architecte' },
  { value: 'geometre', label: 'Géomètre-expert' },
  { value: 'ingenieur_conseil', label: 'Ingénieur conseil' },
  { value: 'consultant_independant', label: 'Consultant indépendant' },
  { value: 'dentiste', label: 'Chirurgien-dentiste, dentiste' },
  { value: 'psychologue', label: 'Psychologue' },
  { value: 'psychologue_clinique', label: 'Psychologue clinicien' },
  { value: 'psychologue_du_travail', label: 'Psychologue du travail' },
  { value: 'psychanalyste', label: 'Psychanalyste' },
  { value: 'osteopathe', label: 'Ostéopathe' },
  { value: 'chiropracteur', label: 'Chiropracteur' },
  { value: 'acupuncteur', label: 'Acupuncteur' },
  { value: 'naturopathe', label: 'Naturopathe' },
  { value: 'sage_femme_liberale', label: 'Sage-femme libérale' },
  { value: 'avocat_specialise', label: 'Avocat spécialisé' },
  { value: 'avocat_affaires', label: 'Avocat d\'affaires' },
  { value: 'avocat_penal', label: 'Avocat pénaliste' },
  { value: 'avocat_familial', label: 'Avocat familial' },
  { value: 'commissaire_priseur', label: 'Commissaire-priseur' },
  { value: 'greffier', label: 'Greffier' },
  { value: 'mandataire_judiciaire', label: 'Mandataire judiciaire' },
  { value: 'administrateur_judiciaire', label: 'Administrateur judiciaire' },
  { value: 'expert_judiciaire', label: 'Expert judiciaire' },
  { value: 'geologue_expert', label: 'Géologue expert' },
  { value: 'ingenieur_agrege', label: 'Ingénieur agréé' },
  
  // Cadres d'entreprise
  { value: 'cadre_entreprise', label: 'Cadre d\'entreprise' },
  { value: 'directeur_general', label: 'Directeur général, PDG' },
  { value: 'directeur_adjoint', label: 'Directeur adjoint' },
  { value: 'directeur_service', label: 'Directeur de service' },
  { value: 'directeur_commercial', label: 'Directeur commercial' },
  { value: 'directeur_marketing', label: 'Directeur marketing' },
  { value: 'directeur_rh', label: 'Directeur des ressources humaines' },
  { value: 'directeur_financier', label: 'Directeur financier' },
  { value: 'directeur_technique', label: 'Directeur technique' },
  { value: 'directeur_production', label: 'Directeur de production' },
  { value: 'directeur_qualite', label: 'Directeur qualité' },
  { value: 'directeur_logistique', label: 'Directeur logistique' },
  { value: 'directeur_achat', label: 'Directeur des achats' },
  { value: 'cadre_sup', label: 'Cadre supérieur' },
  { value: 'cadre_commercial', label: 'Cadre commercial' },
  { value: 'cadre_technique', label: 'Cadre technique' },
  { value: 'cadre_administratif', label: 'Cadre administratif' },
  { value: 'cadre_financier', label: 'Cadre financier' },
  { value: 'cadre_rh', label: 'Cadre ressources humaines' },
  { value: 'cadre_communication', label: 'Cadre communication' },
  { value: 'cadre_informatique', label: 'Cadre informatique' },
  { value: 'cadre_etudes_developpement', label: 'Cadre études et développement informatique' },
  { value: 'cadre_exploitation_informatique', label: 'Cadre exploitation informatique' },
  { value: 'directeur_informatique', label: 'Directeur informatique' },
  { value: 'directeur_systeme_information', label: 'Directeur système d\'information' },
  { value: 'responsable_informatique', label: 'Responsable informatique' },
  { value: 'consultant_informatique', label: 'Consultant informatique' },
  { value: 'expert_informatique', label: 'Expert informatique' },
  { value: 'cadre_recherche', label: 'Cadre recherche et développement' },
  
  // Cadres de la fonction publique
  { value: 'cadre_fonction_publique', label: 'Cadre de la fonction publique' },
  { value: 'cadre_etat', label: 'Cadre de l\'État' },
  { value: 'cadre_collectivite', label: 'Cadre des collectivités territoriales' },
  { value: 'cadre_hospitalier', label: 'Cadre hospitalier' },
  { value: 'directeur_administration', label: 'Directeur d\'administration' },
  { value: 'prefet', label: 'Préfet, sous-préfet' },
  { value: 'diplomate', label: 'Diplomate' },
  
  // Professions de l'information, des arts et des spectacles
  { value: 'journaliste', label: 'Journaliste' },
  { value: 'journaliste_presse', label: 'Journaliste presse écrite' },
  { value: 'journaliste_radio', label: 'Journaliste radio' },
  { value: 'journaliste_tv', label: 'Journaliste télévision' },
  { value: 'journaliste_web', label: 'Journaliste web' },
  { value: 'redacteur', label: 'Rédacteur' },
  { value: 'auteur', label: 'Auteur' },
  { value: 'ecrivain', label: 'Écrivain' },
  { value: 'scenariste', label: 'Scénariste' },
  { value: 'artiste', label: 'Artiste' },
  { value: 'artiste_peintre', label: 'Artiste peintre' },
  { value: 'artiste_sculpteur', label: 'Artiste sculpteur' },
  { value: 'artiste_photographe', label: 'Photographe artiste' },
  { value: 'compositeur', label: 'Compositeur' },
  { value: 'musicien', label: 'Musicien professionnel' },
  { value: 'comedien', label: 'Comédien, acteur' },
  { value: 'metteur_scene', label: 'Metteur en scène' },
  { value: 'realisateur', label: 'Réalisateur' },
  { value: 'producteur', label: 'Producteur audiovisuel' },
  
  // Professions scientifiques
  { value: 'chercheur', label: 'Chercheur, scientifique' },
  { value: 'chercheur_cnrs', label: 'Chercheur CNRS' },
  { value: 'chercheur_universite', label: 'Chercheur universitaire' },
  { value: 'chercheur_industrie', label: 'Chercheur industriel' },
  { value: 'astronome', label: 'Astronome' },
  { value: 'physicien', label: 'Physicien' },
  { value: 'chimiste', label: 'Chimiste' },
  { value: 'biologiste', label: 'Biologiste' },
  { value: 'geologue', label: 'Géologue' },
  { value: 'meteorologue', label: 'Météorologue' },
  
  // Ingénieurs
  { value: 'ingenieur', label: 'Ingénieur' },
  { value: 'ingenieur_industrie', label: 'Ingénieur industriel' },
  { value: 'ingenieur_informatique', label: 'Ingénieur informatique' },
  { value: 'ingenieur_developpement', label: 'Ingénieur développement' },
  { value: 'ingenieur_reseau', label: 'Ingénieur réseau' },
  { value: 'ingenieur_systeme', label: 'Ingénieur système' },
  { value: 'ingenieur_securite_informatique', label: 'Ingénieur sécurité informatique' },
  { value: 'developpeur', label: 'Développeur' },
  { value: 'developpeur_logiciel', label: 'Développeur logiciel' },
  { value: 'developpeur_application', label: 'Développeur d\'application' },
  { value: 'developpeur_web', label: 'Développeur web' },
  { value: 'developpeur_mobile', label: 'Développeur mobile' },
  { value: 'analyste_programmeur', label: 'Analyste-programmeur' },
  { value: 'programmeur', label: 'Programmeur' },
  { value: 'architecte_logiciel', label: 'Architecte logiciel' },
  { value: 'architecte_systeme', label: 'Architecte système' },
  { value: 'chef_projet_informatique', label: 'Chef de projet informatique' },
  { value: 'chef_projet_technique', label: 'Chef de projet technique' },
  { value: 'administrateur_systeme', label: 'Administrateur système' },
  { value: 'administrateur_reseau', label: 'Administrateur réseau' },
  { value: 'administrateur_base_donnees', label: 'Administrateur base de données' },
  { value: 'informaticien', label: 'Informaticien' },
  { value: 'ingenieur_telecom', label: 'Ingénieur télécommunications' },
  { value: 'ingenieur_electronique', label: 'Ingénieur électronique' },
  { value: 'ingenieur_mecanique', label: 'Ingénieur mécanique' },
  { value: 'ingenieur_civil', label: 'Ingénieur civil' },
  { value: 'ingenieur_batiment', label: 'Ingénieur bâtiment' },
  { value: 'ingenieur_genie_civil', label: 'Ingénieur génie civil' },
  { value: 'ingenieur_agronome', label: 'Ingénieur agronome' },
  { value: 'ingenieur_chimiste', label: 'Ingénieur chimiste' },
  { value: 'ingenieur_energie', label: 'Ingénieur énergie' },
  { value: 'ingenieur_environnement', label: 'Ingénieur environnement' },
  { value: 'ingenieur_qualite', label: 'Ingénieur qualité' },
  { value: 'ingenieur_recherche', label: 'Ingénieur recherche et développement' },
  
  // Professeurs et professions scientifiques
  { value: 'professeur_enseignant', label: 'Professeur, enseignant' },
  { value: 'professeur_universite', label: 'Professeur d\'université' },
  { value: 'professeur_cpge', label: 'Professeur de classes préparatoires' },
  { value: 'professeur_lycee', label: 'Professeur de lycée' },
  { value: 'professeur_college', label: 'Professeur de collège' },
  { value: 'professeur_ecole', label: 'Professeur des écoles' },
  { value: 'maitre_formateur', label: 'Maître formateur' },
  { value: 'conseiller_pedagogique', label: 'Conseiller pédagogique' },
  { value: 'inspecteur_education', label: 'Inspecteur de l\'éducation nationale' },
  { value: 'professeur_education_physique', label: 'Professeur d\'éducation physique et sportive' },
  { value: 'professeur_art', label: 'Professeur d\'arts plastiques' },
  { value: 'professeur_musique', label: 'Professeur de musique' },
  { value: 'professeur_langue', label: 'Professeur de langue' },
  { value: 'professeur_technologie', label: 'Professeur de technologie' },
  { value: 'professeur_sciences', label: 'Professeur de sciences' },
  { value: 'professeur_histoire_geo', label: 'Professeur d\'histoire-géographie' },
  { value: 'professeur_philosophie', label: 'Professeur de philosophie' },
  { value: 'professeur_lettres', label: 'Professeur de lettres' },
  { value: 'professeur_mathematiques', label: 'Professeur de mathématiques' },
  { value: 'maitre_nageur', label: 'Maître-nageur sauveteur' },
  { value: 'moniteur_sport', label: 'Moniteur de sport' },
  { value: 'educateur_sportif', label: 'Éducateur sportif' },
  { value: 'entraineur', label: 'Entraîneur' },
  { value: 'coach_sportif', label: 'Coach sportif' },
  
  // ============================================
  // GROUPE 4 : PROFESSIONS INTERMÉDIAIRES
  // ============================================
  // Professions intermédiaires administratives et commerciales des entreprises
  { value: 'prof_intermediaire_admin', label: 'Profession intermédiaire administrative' },
  { value: 'prof_intermediaire_commerciale', label: 'Profession intermédiaire commerciale' },
  { value: 'chef_comptable', label: 'Chef comptable' },
  { value: 'chef_personnel', label: 'Chef du personnel' },
  { value: 'chef_secrétariat', label: 'Chef de secrétariat' },
  { value: 'assistant_direction', label: 'Assistant de direction' },
  { value: 'assistant_rh', label: 'Assistant ressources humaines' },
  { value: 'assistant_commercial', label: 'Assistant commercial' },
  { value: 'assistant_marketing', label: 'Assistant marketing' },
  { value: 'chef_vente', label: 'Chef de vente' },
  { value: 'chef_magasin', label: 'Chef de magasin' },
  { value: 'chef_rayon', label: 'Chef de rayon' },
  { value: 'chef_equipe_commerciale', label: 'Chef d\'équipe commerciale' },
  { value: 'conseiller_client', label: 'Conseiller clientèle' },
  { value: 'conseiller_commercial', label: 'Conseiller commercial' },
  { value: 'conseiller_banque', label: 'Conseiller bancaire' },
  { value: 'conseiller_assurance', label: 'Conseiller assurance' },
  { value: 'courtier', label: 'Courtier' },
  { value: 'courtier_assurance', label: 'Courtier en assurance' },
  { value: 'courtier_immobilier', label: 'Courtier immobilier' },
  { value: 'courtier_maritime', label: 'Courtier maritime' },
  { value: 'courtier_transport', label: 'Courtier en transport' },
  { value: 'agent_immobilier', label: 'Agent immobilier' },
  { value: 'negociateur_immobilier', label: 'Négociateur immobilier' },
  { value: 'gestionnaire_patrimoine', label: 'Gestionnaire de patrimoine' },
  { value: 'conseiller_financier', label: 'Conseiller financier' },
  { value: 'conseiller_investissement', label: 'Conseiller en investissement' },
  { value: 'conseiller_retraite', label: 'Conseiller en retraite' },
  { value: 'conseiller_prevoyance', label: 'Conseiller en prévoyance' },
  { value: 'conseiller_epargne', label: 'Conseiller en épargne' },
  { value: 'conseiller_credits', label: 'Conseiller en crédits' },
  { value: 'charge_client', label: 'Chargé de clientèle' },
  { value: 'charge_affaires', label: 'Chargé d\'affaires' },
  { value: 'charge_projet', label: 'Chargé de projet' },
  { value: 'charge_communication', label: 'Chargé de communication' },
  { value: 'charge_marketing', label: 'Chargé de marketing' },
  { value: 'charge_rh', label: 'Chargé de ressources humaines' },
  { value: 'charge_qualite', label: 'Chargé de qualité' },
  { value: 'charge_achats', label: 'Chargé d\'achats' },
  { value: 'charge_logistique', label: 'Chargé de logistique' },
  { value: 'charge_export', label: 'Chargé d\'export' },
  { value: 'charge_import', label: 'Chargé d\'import' },
  { value: 'responsable_commercial', label: 'Responsable commercial' },
  { value: 'responsable_vente', label: 'Responsable des ventes' },
  { value: 'responsable_magasin', label: 'Responsable de magasin' },
  { value: 'responsable_rayon', label: 'Responsable de rayon' },
  { value: 'responsable_point_vente', label: 'Responsable de point de vente' },
  
  // Techniciens
  { value: 'technicien', label: 'Technicien' },
  { value: 'technicien_informatique', label: 'Technicien informatique' },
  { value: 'technicien_telecom', label: 'Technicien télécommunications' },
  { value: 'technicien_electronique', label: 'Technicien électronique' },
  { value: 'technicien_mecanique', label: 'Technicien mécanique' },
  { value: 'technicien_industrie', label: 'Technicien industriel' },
  { value: 'technicien_laboratoire', label: 'Technicien de laboratoire' },
  { value: 'technicien_qualite', label: 'Technicien qualité' },
  { value: 'technicien_maintenance', label: 'Technicien maintenance' },
  { value: 'technicien_batiment', label: 'Technicien du bâtiment' },
  { value: 'technicien_topographe', label: 'Technicien topographe' },
  { value: 'dessinateur_projeteur', label: 'Dessinateur-projeteur' },
  { value: 'metreur', label: 'Métreur' },
  { value: 'technicien_energie', label: 'Technicien énergie' },
  { value: 'technicien_environnement', label: 'Technicien environnement' },
  { value: 'technicien_telecom_reseau', label: 'Technicien télécoms et réseaux' },
  { value: 'technicien_audiovisuel', label: 'Technicien audiovisuel' },
  { value: 'technicien_son', label: 'Technicien du son' },
  { value: 'technicien_image', label: 'Technicien de l\'image' },
  { value: 'technicien_eclairage', label: 'Technicien éclairage' },
  { value: 'technicien_spectacle', label: 'Technicien spectacle' },
  { value: 'technicien_meteo', label: 'Technicien météorologie' },
  { value: 'technicien_geologie', label: 'Technicien géologie' },
  { value: 'technicien_geophysique', label: 'Technicien géophysique' },
  { value: 'technicien_hydraulique', label: 'Technicien hydraulique' },
  { value: 'technicien_thermique', label: 'Technicien thermique' },
  { value: 'technicien_climatisation', label: 'Technicien climatisation' },
  { value: 'technicien_froid', label: 'Technicien froid' },
  { value: 'technicien_plomberie', label: 'Technicien plomberie' },
  { value: 'technicien_chauffage', label: 'Technicien chauffage' },
  { value: 'technicien_securite', label: 'Technicien sécurité' },
  { value: 'technicien_prevention', label: 'Technicien prévention' },
  { value: 'technicien_controle', label: 'Technicien contrôle' },
  { value: 'technicien_essai', label: 'Technicien essais' },
  { value: 'technicien_mesure', label: 'Technicien mesure' },
  { value: 'technicien_metrologie', label: 'Technicien métrologie' },
  { value: 'technicien_optique', label: 'Technicien optique' },
  { value: 'technicien_photonique', label: 'Technicien photonique' },
  { value: 'technicien_robotique', label: 'Technicien robotique' },
  { value: 'technicien_automatisme', label: 'Technicien automatisme' },
  { value: 'technicien_instrumentation', label: 'Technicien instrumentation' },
  { value: 'technicien_regulation', label: 'Technicien régulation' },
  { value: 'technicien_telematique', label: 'Technicien télématique' },
  { value: 'technicien_telecom_mobile', label: 'Technicien télécoms mobiles' },
  { value: 'technicien_fibre_optique', label: 'Technicien fibre optique' },
  { value: 'technicien_satellite', label: 'Technicien satellite' },
  { value: 'technicien_radar', label: 'Technicien radar' },
  { value: 'technicien_navigation', label: 'Technicien navigation' },
  { value: 'technicien_aeronautique', label: 'Technicien aéronautique' },
  { value: 'technicien_spatial', label: 'Technicien spatial' },
  { value: 'technicien_naval', label: 'Technicien naval' },
  { value: 'technicien_automobile', label: 'Technicien automobile' },
  { value: 'technicien_moto', label: 'Technicien moto' },
  { value: 'technicien_cycle', label: 'Technicien cycle' },
  { value: 'technicien_agricole', label: 'Technicien agricole' },
  { value: 'technicien_agroalimentaire', label: 'Technicien agroalimentaire' },
  { value: 'technicien_biotechnologie', label: 'Technicien biotechnologie' },
  { value: 'technicien_pharmaceutique', label: 'Technicien pharmaceutique' },
  { value: 'technicien_cosmetique', label: 'Technicien cosmétique' },
  { value: 'technicien_textile', label: 'Technicien textile' },
  { value: 'technicien_cuir', label: 'Technicien cuir' },
  { value: 'technicien_papier', label: 'Technicien papier' },
  { value: 'technicien_imprimerie', label: 'Technicien imprimerie' },
  { value: 'technicien_emballage', label: 'Technicien emballage' },
  { value: 'technicien_verre', label: 'Technicien verre' },
  { value: 'technicien_ceramique', label: 'Technicien céramique' },
  { value: 'technicien_plastique', label: 'Technicien plastique' },
  { value: 'technicien_caoutchouc', label: 'Technicien caoutchouc' },
  { value: 'technicien_composite', label: 'Technicien composite' },
  { value: 'technicien_materiaux', label: 'Technicien matériaux' },
  { value: 'technicien_surface', label: 'Technicien traitement de surface' },
  { value: 'technicien_peinture_industrie', label: 'Technicien peinture industrie' },
  { value: 'technicien_galvanoplastie', label: 'Technicien galvanoplastie' },
  { value: 'technicien_traitement_thermique', label: 'Technicien traitement thermique' },
  { value: 'technicien_metallurgie', label: 'Technicien métallurgie' },
  { value: 'technicien_fonderie', label: 'Technicien fonderie' },
  { value: 'technicien_forge', label: 'Technicien forge' },
  { value: 'technicien_usinage', label: 'Technicien usinage' },
  { value: 'technicien_assemblage', label: 'Technicien assemblage' },
  { value: 'technicien_montage', label: 'Technicien montage' },
  { value: 'technicien_cablage', label: 'Technicien câblage' },
  { value: 'technicien_prototypage', label: 'Technicien prototypage' },
  { value: 'technicien_essai_materiel', label: 'Technicien essais matériel' },
  { value: 'technicien_controle_qualite', label: 'Technicien contrôle qualité' },
  { value: 'technicien_metrologie_dimensionnelle', label: 'Technicien métrologie dimensionnelle' },
  { value: 'technicien_essai_destruction', label: 'Technicien essais destruction' },
  { value: 'technicien_essai_non_destruction', label: 'Technicien essais non destructifs' },
  { value: 'technicien_controle_produit', label: 'Technicien contrôle produit' },
  { value: 'technicien_controle_process', label: 'Technicien contrôle processus' },
  { value: 'technicien_controle_environnement', label: 'Technicien contrôle environnement' },
  { value: 'technicien_controle_securite', label: 'Technicien contrôle sécurité' },
  { value: 'technicien_controle_hygiene', label: 'Technicien contrôle hygiène' },
  { value: 'technicien_controle_alimentaire', label: 'Technicien contrôle alimentaire' },
  { value: 'technicien_controle_pharmaceutique', label: 'Technicien contrôle pharmaceutique' },
  { value: 'technicien_controle_cosmetique', label: 'Technicien contrôle cosmétique' },
  { value: 'technicien_controle_textile', label: 'Technicien contrôle textile' },
  { value: 'technicien_controle_automobile', label: 'Technicien contrôle automobile' },
  { value: 'technicien_controle_aeronautique', label: 'Technicien contrôle aéronautique' },
  { value: 'technicien_controle_naval', label: 'Technicien contrôle naval' },
  { value: 'technicien_controle_ferroviaire', label: 'Technicien contrôle ferroviaire' },
  { value: 'technicien_controle_energie', label: 'Technicien contrôle énergie' },
  { value: 'technicien_controle_nucleaire', label: 'Technicien contrôle nucléaire' },
  { value: 'technicien_controle_renouvelable', label: 'Technicien contrôle énergies renouvelables' },
  { value: 'technicien_maintenance_preventive', label: 'Technicien maintenance préventive' },
  { value: 'technicien_maintenance_corrective', label: 'Technicien maintenance corrective' },
  { value: 'technicien_maintenance_predictive', label: 'Technicien maintenance prédictive' },
  { value: 'technicien_maintenance_industrielle', label: 'Technicien maintenance industrielle' },
  { value: 'technicien_maintenance_batiment', label: 'Technicien maintenance bâtiment' },
  { value: 'technicien_maintenance_ascenseur', label: 'Technicien maintenance ascenseurs' },
  { value: 'technicien_maintenance_climatisation', label: 'Technicien maintenance climatisation' },
  { value: 'technicien_maintenance_chauffage', label: 'Technicien maintenance chauffage' },
  { value: 'technicien_maintenance_plomberie', label: 'Technicien maintenance plomberie' },
  { value: 'technicien_maintenance_electricite', label: 'Technicien maintenance électricité' },
  { value: 'technicien_maintenance_electronique', label: 'Technicien maintenance électronique' },
  { value: 'technicien_maintenance_informatique', label: 'Technicien maintenance informatique' },
  { value: 'technicien_support_informatique', label: 'Technicien support informatique' },
  { value: 'technicien_reseau', label: 'Technicien réseau' },
  { value: 'technicien_telecom', label: 'Technicien télécommunications' },
  { value: 'technicien_helpdesk', label: 'Technicien helpdesk' },
  { value: 'operateur_informatique', label: 'Opérateur informatique' },
  { value: 'technicien_maintenance_telecom', label: 'Technicien maintenance télécoms' },
  { value: 'technicien_maintenance_automobile', label: 'Technicien maintenance automobile' },
  { value: 'technicien_maintenance_moto', label: 'Technicien maintenance moto' },
  { value: 'technicien_maintenance_cycle', label: 'Technicien maintenance cycle' },
  { value: 'technicien_maintenance_aeronautique', label: 'Technicien maintenance aéronautique' },
  { value: 'technicien_maintenance_navale', label: 'Technicien maintenance navale' },
  { value: 'technicien_maintenance_ferroviaire', label: 'Technicien maintenance ferroviaire' },
  { value: 'technicien_maintenance_engin_tp', label: 'Technicien maintenance engins TP' },
  { value: 'technicien_maintenance_agricole', label: 'Technicien maintenance agricole' },
  { value: 'technicien_maintenance_medicale', label: 'Technicien maintenance médicale' },
  { value: 'technicien_maintenance_laboratoire', label: 'Technicien maintenance laboratoire' },
  { value: 'technicien_maintenance_pharmaceutique', label: 'Technicien maintenance pharmaceutique' },
  { value: 'technicien_maintenance_agroalimentaire', label: 'Technicien maintenance agroalimentaire' },
  { value: 'technicien_maintenance_textile', label: 'Technicien maintenance textile' },
  { value: 'technicien_maintenance_imprimerie', label: 'Technicien maintenance imprimerie' },
  { value: 'technicien_maintenance_emballage', label: 'Technicien maintenance emballage' },
  { value: 'technicien_maintenance_verre', label: 'Technicien maintenance verre' },
  { value: 'technicien_maintenance_ceramique', label: 'Technicien maintenance céramique' },
  { value: 'technicien_maintenance_plastique', label: 'Technicien maintenance plastique' },
  { value: 'technicien_maintenance_caoutchouc', label: 'Technicien maintenance caoutchouc' },
  { value: 'technicien_maintenance_composite', label: 'Technicien maintenance composite' },
  { value: 'technicien_maintenance_materiaux', label: 'Technicien maintenance matériaux' },
  { value: 'technicien_maintenance_surface', label: 'Technicien maintenance traitement de surface' },
  { value: 'technicien_maintenance_peinture', label: 'Technicien maintenance peinture' },
  { value: 'technicien_maintenance_galvanoplastie', label: 'Technicien maintenance galvanoplastie' },
  { value: 'technicien_maintenance_traitement_thermique', label: 'Technicien maintenance traitement thermique' },
  { value: 'technicien_maintenance_metallurgie', label: 'Technicien maintenance métallurgie' },
  { value: 'technicien_maintenance_fonderie', label: 'Technicien maintenance fonderie' },
  { value: 'technicien_maintenance_forge', label: 'Technicien maintenance forge' },
  { value: 'technicien_maintenance_usinage', label: 'Technicien maintenance usinage' },
  { value: 'technicien_maintenance_assemblage', label: 'Technicien maintenance assemblage' },
  { value: 'technicien_maintenance_montage', label: 'Technicien maintenance montage' },
  { value: 'technicien_maintenance_cablage', label: 'Technicien maintenance câblage' },
  { value: 'technicien_maintenance_prototypage', label: 'Technicien maintenance prototypage' },
  { value: 'technicien_maintenance_essai', label: 'Technicien maintenance essais' },
  { value: 'technicien_maintenance_controle_qualite', label: 'Technicien maintenance contrôle qualité' },
  { value: 'technicien_maintenance_metrologie', label: 'Technicien maintenance métrologie' },
  { value: 'technicien_maintenance_essai_destruction', label: 'Technicien maintenance essais destruction' },
  { value: 'technicien_maintenance_essai_non_destruction', label: 'Technicien maintenance essais non destructifs' },
  { value: 'technicien_maintenance_controle_produit', label: 'Technicien maintenance contrôle produit' },
  { value: 'technicien_maintenance_controle_process', label: 'Technicien maintenance contrôle processus' },
  { value: 'technicien_maintenance_controle_environnement', label: 'Technicien maintenance contrôle environnement' },
  { value: 'technicien_maintenance_controle_securite', label: 'Technicien maintenance contrôle sécurité' },
  { value: 'technicien_maintenance_controle_hygiene', label: 'Technicien maintenance contrôle hygiène' },
  { value: 'technicien_maintenance_controle_alimentaire', label: 'Technicien maintenance contrôle alimentaire' },
  { value: 'technicien_maintenance_controle_pharmaceutique', label: 'Technicien maintenance contrôle pharmaceutique' },
  { value: 'technicien_maintenance_controle_cosmetique', label: 'Technicien maintenance contrôle cosmétique' },
  { value: 'technicien_maintenance_controle_textile', label: 'Technicien maintenance contrôle textile' },
  { value: 'technicien_maintenance_controle_automobile', label: 'Technicien maintenance contrôle automobile' },
  { value: 'technicien_maintenance_controle_aeronautique', label: 'Technicien maintenance contrôle aéronautique' },
  { value: 'technicien_maintenance_controle_naval', label: 'Technicien maintenance contrôle naval' },
  { value: 'technicien_maintenance_controle_ferroviaire', label: 'Technicien maintenance contrôle ferroviaire' },
  { value: 'technicien_maintenance_controle_energie', label: 'Technicien maintenance contrôle énergie' },
  { value: 'technicien_maintenance_controle_nucleaire', label: 'Technicien maintenance contrôle nucléaire' },
  { value: 'technicien_maintenance_controle_renouvelable', label: 'Technicien maintenance contrôle énergies renouvelables' },
  
  // Contremaîtres et agents de maîtrise
  { value: 'contremaitre', label: 'Contremaître, agent de maîtrise' },
  { value: 'contremaitre_industrie', label: 'Contremaître industrie' },
  { value: 'contremaitre_batiment', label: 'Contremaître bâtiment' },
  { value: 'chef_atelier', label: 'Chef d\'atelier' },
  { value: 'chef_equipe', label: 'Chef d\'équipe' },
  { value: 'agent_maitrise', label: 'Agent de maîtrise' },
  { value: 'agent_maitrise_industrie', label: 'Agent de maîtrise industrie' },
  { value: 'agent_maitrise_batiment', label: 'Agent de maîtrise bâtiment' },
  
  // Professions intermédiaires de la santé et du travail social
  { value: 'infirmier', label: 'Infirmier, sage-femme' },
  { value: 'infirmier_liberal', label: 'Infirmier libéral' },
  { value: 'infirmier_hopital', label: 'Infirmier hospitalier' },
  { value: 'infirmier_soins', label: 'Infirmier de soins' },
  { value: 'infirmier_bloc', label: 'Infirmier de bloc opératoire' },
  { value: 'infirmier_anesthesie', label: 'Infirmier anesthésiste' },
  { value: 'sage_femme', label: 'Sage-femme' },
  { value: 'masseur_kinesitherapeute', label: 'Masseur-kinésithérapeute' },
  { value: 'pedicure_podologue', label: 'Pédicure-podologue' },
  { value: 'orthoptiste', label: 'Orthoptiste' },
  { value: 'orthophoniste', label: 'Orthophoniste' },
  { value: 'psychomotricien', label: 'Psychomotricien' },
  { value: 'ergotherapeute', label: 'Ergothérapeute' },
  { value: 'dieteticien', label: 'Diététicien' },
  { value: 'technicien_radio', label: 'Technicien en radiologie' },
  { value: 'technicien_biologie', label: 'Technicien de laboratoire médical' },
  { value: 'prof_paramedical', label: 'Profession paramédicale' },
  { value: 'prof_intermediaire_sante', label: 'Profession intermédiaire de la santé' },
  { value: 'prof_intermediaire_social', label: 'Profession intermédiaire du travail social' },
  { value: 'educateur', label: 'Éducateur' },
  { value: 'educateur_specialise', label: 'Éducateur spécialisé' },
  { value: 'educateur_jeunes', label: 'Éducateur de jeunes enfants' },
  { value: 'moniteur_educateur', label: 'Moniteur-éducateur' },
  { value: 'animateur', label: 'Animateur socioculturel' },
  { value: 'assistant_social', label: 'Assistant social' },
  { value: 'conseiller_insertion', label: 'Conseiller en insertion' },
  { value: 'conseiller_familial', label: 'Conseiller conjugal et familial' },
  { value: 'manipulateur_radio', label: 'Manipulateur en électroradiologie médicale' },
  { value: 'preparateur_pharmacie', label: 'Préparateur en pharmacie' },
  { value: 'opticien_lunetier', label: 'Opticien-lunetier' },
  { value: 'audioprothesiste', label: 'Audioprothésiste' },
  { value: 'orthoprothesiste', label: 'Orthoprothésiste' },
  { value: 'prothesiste_dentaire', label: 'Prothésiste dentaire' },
  { value: 'prothesiste_orthopedique', label: 'Prothésiste orthopédique' },
  { value: 'prothesiste_oculaire', label: 'Prothésiste oculaire' },
  { value: 'prothesiste_orthopedique_reinsertion_professionnelle', label: 'Prothésiste orthopédique réinsertion professionnelle' },
  { value: 'prothesiste_orthopedique_reinsertion_sociale', label: 'Prothésiste orthopédique réinsertion sociale' },
  { value: 'prothesiste_orthopedique_reinsertion_familiale', label: 'Prothésiste orthopédique réinsertion familiale' },
  { value: 'prothesiste_orthopedique_reinsertion_scolaire', label: 'Prothésiste orthopédique réinsertion scolaire' },
  { value: 'prothesiste_orthopedique_reinsertion_sportive', label: 'Prothésiste orthopédique réinsertion sportive' },
  { value: 'prothesiste_orthopedique_reinsertion_culturelle', label: 'Prothésiste orthopédique réinsertion culturelle' },
  { value: 'prothesiste_orthopedique_reinsertion_loisir', label: 'Prothésiste orthopédique réinsertion loisir' },
  { value: 'prothesiste_orthopedique_reinsertion_voyage', label: 'Prothésiste orthopédique réinsertion voyage' },
  { value: 'prothesiste_orthopedique_reinsertion_domicile', label: 'Prothésiste orthopédique réinsertion domicile' },
  { value: 'prothesiste_orthopedique_reinsertion_transport', label: 'Prothésiste orthopédique réinsertion transport' },
  { value: 'prothesiste_orthopedique_reinsertion_accessibilite', label: 'Prothésiste orthopédique réinsertion accessibilité' },
  { value: 'prothesiste_orthopedique_reinsertion_autonomie', label: 'Prothésiste orthopédique réinsertion autonomie' },
  { value: 'prothesiste_orthopedique_reinsertion_independance', label: 'Prothésiste orthopédique réinsertion indépendance' },
  { value: 'prothesiste_orthopedique_reinsertion_qualite_vie', label: 'Prothésiste orthopédique réinsertion qualité de vie' },
  { value: 'prothesiste_orthopedique_reinsertion_bien_etre', label: 'Prothésiste orthopédique réinsertion bien-être' },
  { value: 'prothesiste_orthopedique_reinsertion_sante', label: 'Prothésiste orthopédique réinsertion santé' },
  { value: 'prothesiste_orthopedique_reinsertion_prevention', label: 'Prothésiste orthopédique réinsertion prévention' },
  { value: 'prothesiste_orthopedique_reinsertion_soins', label: 'Prothésiste orthopédique réinsertion soins' },
  { value: 'prothesiste_orthopedique_reinsertion_accompagnement', label: 'Prothésiste orthopédique réinsertion accompagnement' },
  { value: 'prothesiste_orthopedique_reinsertion_suivi', label: 'Prothésiste orthopédique réinsertion suivi' },
  { value: 'prothesiste_orthopedique_reinsertion_evaluation', label: 'Prothésiste orthopédique réinsertion évaluation' },
  { value: 'prothesiste_orthopedique_reinsertion_adaptation', label: 'Prothésiste orthopédique réinsertion adaptation' },
  { value: 'prothesiste_orthopedique_reinsertion_ajustement', label: 'Prothésiste orthopédique réinsertion ajustement' },
  { value: 'prothesiste_orthopedique_reinsertion_reglage', label: 'Prothésiste orthopédique réinsertion réglage' },
  { value: 'prothesiste_orthopedique_reinsertion_entretien', label: 'Prothésiste orthopédique réinsertion entretien' },
  { value: 'prothesiste_orthopedique_reinsertion_reparation', label: 'Prothésiste orthopédique réinsertion réparation' },
  { value: 'prothesiste_orthopedique_reinsertion_remplacement', label: 'Prothésiste orthopédique réinsertion remplacement' },
  { value: 'prothesiste_orthopedique_reinsertion_renouvellement', label: 'Prothésiste orthopédique réinsertion renouvellement' },
  { value: 'prothesiste_orthopedique_reinsertion_evolution', label: 'Prothésiste orthopédique réinsertion évolution' },
  { value: 'prothesiste_orthopedique_reinsertion_innovation', label: 'Prothésiste orthopédique réinsertion innovation' },
  { value: 'prothesiste_orthopedique_reinsertion_recherche', label: 'Prothésiste orthopédique réinsertion recherche' },
  { value: 'prothesiste_orthopedique_reinsertion_developpement', label: 'Prothésiste orthopédique réinsertion développement' },
  { value: 'prothesiste_orthopedique_reinsertion_formation', label: 'Prothésiste orthopédique réinsertion formation' },
  { value: 'prothesiste_orthopedique_reinsertion_enseignement', label: 'Prothésiste orthopédique réinsertion enseignement' },
  { value: 'prothesiste_orthopedique_reinsertion_information', label: 'Prothésiste orthopédique réinsertion information' },
  { value: 'prothesiste_orthopedique_reinsertion_communication', label: 'Prothésiste orthopédique réinsertion communication' },
  { value: 'prothesiste_orthopedique_reinsertion_sensibilisation', label: 'Prothésiste orthopédique réinsertion sensibilisation' },
  { value: 'prothesiste_orthopedique_reinsertion_prevention_secondaire', label: 'Prothésiste orthopédique réinsertion prévention secondaire' },
  { value: 'prothesiste_orthopedique_reinsertion_prevention_tertiaire', label: 'Prothésiste orthopédique réinsertion prévention tertiaire' },
  { value: 'prothesiste_orthopedique_reinsertion_prevention_primaire', label: 'Prothésiste orthopédique réinsertion prévention primaire' },
  { value: 'prothesiste_orthopedique_reinsertion_promotion_sante', label: 'Prothésiste orthopédique réinsertion promotion santé' },
  { value: 'prothesiste_orthopedique_reinsertion_education_sante', label: 'Prothésiste orthopédique réinsertion éducation santé' },
  { value: 'prothesiste_orthopedique_reinsertion_education_therapeutique', label: 'Prothésiste orthopédique réinsertion éducation thérapeutique' },
  { value: 'prothesiste_orthopedique_reinsertion_education_patient', label: 'Prothésiste orthopédique réinsertion éducation patient' },
  { value: 'prothesiste_orthopedique_reinsertion_education_famille', label: 'Prothésiste orthopédique réinsertion éducation famille' },
  { value: 'prothesiste_orthopedique_reinsertion_education_proche', label: 'Prothésiste orthopédique réinsertion éducation proche' },
  { value: 'prothesiste_orthopedique_reinsertion_education_aidant', label: 'Prothésiste orthopédique réinsertion éducation aidant' },
  { value: 'prothesiste_orthopedique_reinsertion_education_caregiver', label: 'Prothésiste orthopédique réinsertion éducation caregiver' },
  { value: 'prothesiste_orthopedique_reinsertion_education_accompagnant', label: 'Prothésiste orthopédique réinsertion éducation accompagnant' },
  { value: 'prothesiste_orthopedique_reinsertion_education_intervenant', label: 'Prothésiste orthopédique réinsertion éducation intervenant' },
  { value: 'prothesiste_orthopedique_reinsertion_education_professionnel', label: 'Prothésiste orthopédique réinsertion éducation professionnel' },
  { value: 'prothesiste_orthopedique_reinsertion_education_soignant', label: 'Prothésiste orthopédique réinsertion éducation soignant' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin', label: 'Prothésiste orthopédique réinsertion éducation médecin' },
  { value: 'prothesiste_orthopedique_reinsertion_education_infirmier', label: 'Prothésiste orthopédique réinsertion éducation infirmier' },
  { value: 'prothesiste_orthopedique_reinsertion_education_kinesitherapeute', label: 'Prothésiste orthopédique réinsertion éducation kinésithérapeute' },
  { value: 'prothesiste_orthopedique_reinsertion_education_ergotherapeute', label: 'Prothésiste orthopédique réinsertion éducation ergothérapeute' },
  { value: 'prothesiste_orthopedique_reinsertion_education_psychomotricien', label: 'Prothésiste orthopédique réinsertion éducation psychomotricien' },
  { value: 'prothesiste_orthopedique_reinsertion_education_orthophoniste', label: 'Prothésiste orthopédique réinsertion éducation orthophoniste' },
  { value: 'prothesiste_orthopedique_reinsertion_education_orthoptiste', label: 'Prothésiste orthopédique réinsertion éducation orthoptiste' },
  { value: 'prothesiste_orthopedique_reinsertion_education_pedicure_podologue', label: 'Prothésiste orthopédique réinsertion éducation pédicure-podologue' },
  { value: 'prothesiste_orthopedique_reinsertion_education_dieteticien', label: 'Prothésiste orthopédique réinsertion éducation diététicien' },
  { value: 'prothesiste_orthopedique_reinsertion_education_assistant_social', label: 'Prothésiste orthopédique réinsertion éducation assistant social' },
  { value: 'prothesiste_orthopedique_reinsertion_education_educateur', label: 'Prothésiste orthopédique réinsertion éducation éducateur' },
  { value: 'prothesiste_orthopedique_reinsertion_education_animateur', label: 'Prothésiste orthopédique réinsertion éducation animateur' },
  { value: 'prothesiste_orthopedique_reinsertion_education_conseiller', label: 'Prothésiste orthopédique réinsertion éducation conseiller' },
  { value: 'prothesiste_orthopedique_reinsertion_education_psychologue', label: 'Prothésiste orthopédique réinsertion éducation psychologue' },
  { value: 'prothesiste_orthopedique_reinsertion_education_psychiatre', label: 'Prothésiste orthopédique réinsertion éducation psychiatre' },
  { value: 'prothesiste_orthopedique_reinsertion_education_neurologue', label: 'Prothésiste orthopédique réinsertion éducation neurologue' },
  { value: 'prothesiste_orthopedique_reinsertion_education_rhumatologue', label: 'Prothésiste orthopédique réinsertion éducation rhumatologue' },
  { value: 'prothesiste_orthopedique_reinsertion_education_traumatologue', label: 'Prothésiste orthopédique réinsertion éducation traumatologue' },
  { value: 'prothesiste_orthopedique_reinsertion_education_chirurgien_orthopedique', label: 'Prothésiste orthopédique réinsertion éducation chirurgien orthopédique' },
  { value: 'prothesiste_orthopedique_reinsertion_education_chirurgien_plastique', label: 'Prothésiste orthopédique réinsertion éducation chirurgien plastique' },
  { value: 'prothesiste_orthopedique_reinsertion_education_chirurgien_reconstructeur', label: 'Prothésiste orthopédique réinsertion éducation chirurgien reconstructeur' },
  { value: 'prothesiste_orthopedique_reinsertion_education_chirurgien_esthetique', label: 'Prothésiste orthopédique réinsertion éducation chirurgien esthétique' },
  { value: 'prothesiste_orthopedique_reinsertion_education_chirurgien_maxillo_facial', label: 'Prothésiste orthopédique réinsertion éducation chirurgien maxillo-facial' },
  { value: 'prothesiste_orthopedique_reinsertion_education_chirurgien_oral', label: 'Prothésiste orthopédique réinsertion éducation chirurgien oral' },
  { value: 'prothesiste_orthopedique_reinsertion_education_chirurgien_dentaire', label: 'Prothésiste orthopédique réinsertion éducation chirurgien-dentaire' },
  { value: 'prothesiste_orthopedique_reinsertion_education_dentiste', label: 'Prothésiste orthopédique réinsertion éducation dentiste' },
  { value: 'prothesiste_orthopedique_reinsertion_education_stomatologue', label: 'Prothésiste orthopédique réinsertion éducation stomatologue' },
  { value: 'prothesiste_orthopedique_reinsertion_education_oculiste', label: 'Prothésiste orthopédique réinsertion éducation oculiste' },
  { value: 'prothesiste_orthopedique_reinsertion_education_ophtalmologue', label: 'Prothésiste orthopédique réinsertion éducation ophtalmologue' },
  { value: 'prothesiste_orthopedique_reinsertion_education_orl', label: 'Prothésiste orthopédique réinsertion éducation ORL' },
  { value: 'prothesiste_orthopedique_reinsertion_education_oto_rhino_laryngologiste', label: 'Prothésiste orthopédique réinsertion éducation oto-rhino-laryngologiste' },
  { value: 'prothesiste_orthopedique_reinsertion_education_dermatologue', label: 'Prothésiste orthopédique réinsertion éducation dermatologue' },
  { value: 'prothesiste_orthopedique_reinsertion_education_allergologue', label: 'Prothésiste orthopédique réinsertion éducation allergologue' },
  { value: 'prothesiste_orthopedique_reinsertion_education_immunologue', label: 'Prothésiste orthopédique réinsertion éducation immunologue' },
  { value: 'prothesiste_orthopedique_reinsertion_education_endocrinologue', label: 'Prothésiste orthopédique réinsertion éducation endocrinologue' },
  { value: 'prothesiste_orthopedique_reinsertion_education_diabetologue', label: 'Prothésiste orthopédique réinsertion éducation diabétologue' },
  { value: 'prothesiste_orthopedique_reinsertion_education_nutritionniste', label: 'Prothésiste orthopédique réinsertion éducation nutritionniste' },
  { value: 'prothesiste_orthopedique_reinsertion_education_gastro_enterologue', label: 'Prothésiste orthopédique réinsertion éducation gastro-entérologue' },
  { value: 'prothesiste_orthopedique_reinsertion_education_hepatologue', label: 'Prothésiste orthopédique réinsertion éducation hépatologue' },
  { value: 'prothesiste_orthopedique_reinsertion_education_nephrologue', label: 'Prothésiste orthopédique réinsertion éducation néphrologue' },
  { value: 'prothesiste_orthopedique_reinsertion_education_urologue', label: 'Prothésiste orthopédique réinsertion éducation urologue' },
  { value: 'prothesiste_orthopedique_reinsertion_education_andrologue', label: 'Prothésiste orthopédique réinsertion éducation andrologue' },
  { value: 'prothesiste_orthopedique_reinsertion_education_gynecologue', label: 'Prothésiste orthopédique réinsertion éducation gynécologue' },
  { value: 'prothesiste_orthopedique_reinsertion_education_obstetricien', label: 'Prothésiste orthopédique réinsertion éducation obstétricien' },
  { value: 'prothesiste_orthopedique_reinsertion_education_pediatre', label: 'Prothésiste orthopédique réinsertion éducation pédiatre' },
  { value: 'prothesiste_orthopedique_reinsertion_education_neonatologue', label: 'Prothésiste orthopédique réinsertion éducation néonatologue' },
  { value: 'prothesiste_orthopedique_reinsertion_education_geriatre', label: 'Prothésiste orthopédique réinsertion éducation gériatre' },
  { value: 'prothesiste_orthopedique_reinsertion_education_gerontologue', label: 'Prothésiste orthopédique réinsertion éducation gérontologue' },
  { value: 'prothesiste_orthopedique_reinsertion_education_oncologue', label: 'Prothésiste orthopédique réinsertion éducation oncologue' },
  { value: 'prothesiste_orthopedique_reinsertion_education_cancérologue', label: 'Prothésiste orthopédique réinsertion éducation cancérologue' },
  { value: 'prothesiste_orthopedique_reinsertion_education_hematologue', label: 'Prothésiste orthopédique réinsertion éducation hématologue' },
  { value: 'prothesiste_orthopedique_reinsertion_education_transfusionniste', label: 'Prothésiste orthopédique réinsertion éducation transfusionniste' },
  { value: 'prothesiste_orthopedique_reinsertion_education_anesthesiste', label: 'Prothésiste orthopédique réinsertion éducation anesthésiste' },
  { value: 'prothesiste_orthopedique_reinsertion_education_reanimateur', label: 'Prothésiste orthopédique réinsertion éducation réanimateur' },
  { value: 'prothesiste_orthopedique_reinsertion_education_intensiviste', label: 'Prothésiste orthopédique réinsertion éducation intensiviste' },
  { value: 'prothesiste_orthopedique_reinsertion_education_urgentiste', label: 'Prothésiste orthopédique réinsertion éducation urgentiste' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_urgence', label: 'Prothésiste orthopédique réinsertion éducation médecin urgence' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_generaliste', label: 'Prothésiste orthopédique réinsertion éducation médecin généraliste' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_famille', label: 'Prothésiste orthopédique réinsertion éducation médecin famille' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_travail', label: 'Prothésiste orthopédique réinsertion éducation médecin travail' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_scolaire', label: 'Prothésiste orthopédique réinsertion éducation médecin scolaire' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_sport', label: 'Prothésiste orthopédique réinsertion éducation médecin sport' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_aviation', label: 'Prothésiste orthopédique réinsertion éducation médecin aviation' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_maritime', label: 'Prothésiste orthopédique réinsertion éducation médecin maritime' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_armee', label: 'Prothésiste orthopédique réinsertion éducation médecin armée' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_penitentiaire', label: 'Prothésiste orthopédique réinsertion éducation médecin pénitentiaire' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_judiciaire', label: 'Prothésiste orthopédique réinsertion éducation médecin judiciaire' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_legiste', label: 'Prothésiste orthopédique réinsertion éducation médecin légiste' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_expert', label: 'Prothésiste orthopédique réinsertion éducation médecin expert' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_conseil', label: 'Prothésiste orthopédique réinsertion éducation médecin conseil' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_agrege', label: 'Prothésiste orthopédique réinsertion éducation médecin agrégé' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_chef', label: 'Prothésiste orthopédique réinsertion éducation médecin chef' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_directeur', label: 'Prothésiste orthopédique réinsertion éducation médecin directeur' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_responsable', label: 'Prothésiste orthopédique réinsertion éducation médecin responsable' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_coordinateur', label: 'Prothésiste orthopédique réinsertion éducation médecin coordinateur' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_referent', label: 'Prothésiste orthopédique réinsertion éducation médecin référent' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_traitant', label: 'Prothésiste orthopédique réinsertion éducation médecin traitant' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_specialiste', label: 'Prothésiste orthopédique réinsertion éducation médecin spécialiste' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_hospitalier', label: 'Prothésiste orthopédique réinsertion éducation médecin hospitalier' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_liberal', label: 'Prothésiste orthopédique réinsertion éducation médecin libéral' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_salarie', label: 'Prothésiste orthopédique réinsertion éducation médecin salarié' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_remplaçant', label: 'Prothésiste orthopédique réinsertion éducation médecin remplaçant' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_interim', label: 'Prothésiste orthopédique réinsertion éducation médecin intérim' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_volontaire', label: 'Prothésiste orthopédique réinsertion éducation médecin volontaire' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_benevole', label: 'Prothésiste orthopédique réinsertion éducation médecin bénévole' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_humanitaire', label: 'Prothésiste orthopédique réinsertion éducation médecin humanitaire' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_cooperation', label: 'Prothésiste orthopédique réinsertion éducation médecin coopération' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_mission', label: 'Prothésiste orthopédique réinsertion éducation médecin mission' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_expatrie', label: 'Prothésiste orthopédique réinsertion éducation médecin expatrié' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_etranger', label: 'Prothésiste orthopédique réinsertion éducation médecin étranger' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_francais', label: 'Prothésiste orthopédique réinsertion éducation médecin français' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_europeen', label: 'Prothésiste orthopédique réinsertion éducation médecin européen' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_international', label: 'Prothésiste orthopédique réinsertion éducation médecin international' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_mondial', label: 'Prothésiste orthopédique réinsertion éducation médecin mondial' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_universel', label: 'Prothésiste orthopédique réinsertion éducation médecin universel' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_global', label: 'Prothésiste orthopédique réinsertion éducation médecin global' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_local', label: 'Prothésiste orthopédique réinsertion éducation médecin local' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_regional', label: 'Prothésiste orthopédique réinsertion éducation médecin régional' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_national', label: 'Prothésiste orthopédique réinsertion éducation médecin national' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_international', label: 'Prothésiste orthopédique réinsertion éducation médecin international' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_mondial', label: 'Prothésiste orthopédique réinsertion éducation médecin mondial' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_universel', label: 'Prothésiste orthopédique réinsertion éducation médecin universel' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_global', label: 'Prothésiste orthopédique réinsertion éducation médecin global' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_local', label: 'Prothésiste orthopédique réinsertion éducation médecin local' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_regional', label: 'Prothésiste orthopédique réinsertion éducation médecin régional' },
  { value: 'prothesiste_orthopedique_reinsertion_education_medecin_national', label: 'Prothésiste orthopédique réinsertion éducation médecin national' },
  
  // Professions intermédiaires de la fonction publique
  { value: 'instituteur', label: 'Instituteur, professeur des écoles' },
  { value: 'professeur_ecole_maternelle', label: 'Professeur des écoles maternelle' },
  { value: 'professeur_ecole_primaire', label: 'Professeur des écoles primaire' },
  { value: 'maitre_auxiliaire', label: 'Maître auxiliaire' },
  { value: 'prof_intermediaire_education', label: 'Profession intermédiaire de l\'éducation' },
  { value: 'conseiller_orientation', label: 'Conseiller d\'orientation' },
  { value: 'documentaliste', label: 'Documentaliste' },
  { value: 'bibliothecaire', label: 'Bibliothécaire' },
  { value: 'archiviste', label: 'Archiviste' },
  
  // Forces armées, police, pompiers
  { value: 'policier_gendarme', label: 'Policier, gendarme' },
  { value: 'policier_national', label: 'Policier national' },
  { value: 'gendarme', label: 'Gendarme' },
  { value: 'gardien_paix', label: 'Gardien de la paix' },
  { value: 'brigadier', label: 'Brigadier de police' },
  { value: 'officier_police', label: 'Officier de police' },
  { value: 'officier_gendarmerie', label: 'Officier de gendarmerie' },
  { value: 'pompier', label: 'Pompier' },
  { value: 'pompier_professionnel', label: 'Pompier professionnel' },
  { value: 'sapeur_pompier', label: 'Sapeur-pompier' },
  { value: 'officier_pompier', label: 'Officier de sapeurs-pompiers' },
  { value: 'militaire_sous_officier', label: 'Militaire sous-officier' },
  { value: 'militaire_officier', label: 'Militaire officier' },
  { value: 'garde_penitentiaire', label: 'Gardien de prison' },
  { value: 'surveillant_penitentiaire', label: 'Surveillant pénitentiaire' },
  { value: 'douanier', label: 'Douanier' },
  { value: 'agent_douane', label: 'Agent des douanes' },
  
  // ============================================
  // GROUPE 5 : EMPLOYÉS
  // ============================================
  // Employés administratifs d'entreprise
  { value: 'employe_admin_entreprise', label: 'Employé administratif d\'entreprise' },
  { value: 'secretaire', label: 'Secrétaire' },
  { value: 'secretaire_direction', label: 'Secrétaire de direction' },
  { value: 'secretaire_comptable', label: 'Secrétaire comptable' },
  { value: 'secretaire_medical', label: 'Secrétaire médical' },
  { value: 'assistant_secretariat', label: 'Assistant secrétariat' },
  { value: 'standardiste', label: 'Standardiste, téléphoniste' },
  { value: 'operateur_saisie', label: 'Opérateur de saisie' },
  { value: 'agent_accueil', label: 'Agent d\'accueil' },
  { value: 'hote_hotesse', label: 'Hôte, hôtesse d\'accueil' },
  { value: 'employe_bureau', label: 'Employé de bureau' },
  { value: 'employe_comptabilite', label: 'Employé de comptabilité' },
  { value: 'employe_personnel', label: 'Employé du personnel' },
  { value: 'employe_archivage', label: 'Employé d\'archivage' },
  
  // Employés de commerce
  { value: 'employe_commercial', label: 'Employé de commerce' },
  { value: 'vendeur', label: 'Vendeur' },
  { value: 'vendeur_specialise', label: 'Vendeur spécialisé' },
  { value: 'vendeur_multimedia', label: 'Vendeur multimédia' },
  { value: 'vendeur_automobile', label: 'Vendeur automobile' },
  { value: 'vendeur_immobilier', label: 'Vendeur immobilier' },
  { value: 'caissier', label: 'Caissier, employé de libre-service' },
  { value: 'caissier_supermarche', label: 'Caissier de supermarché' },
  { value: 'hote_caisse', label: 'Hôte de caisse' },
  { value: 'employe_libre_service', label: 'Employé de libre-service' },
  { value: 'employe_rayon', label: 'Employé de rayon' },
  { value: 'employe_magasin', label: 'Employé de magasin' },
  { value: 'employe_grande_surface', label: 'Employé de grande surface' },
  { value: 'teleconseiller', label: 'Téléconseiller' },
  { value: 'teleoperateur', label: 'Téléopérateur' },
  { value: 'conseiller_telephonique', label: 'Conseiller téléphonique' },
  
  // Employés de la fonction publique
  { value: 'employe_admin_fonction_publique', label: 'Employé administratif de la fonction publique' },
  { value: 'agent_fonction_publique', label: 'Agent de la fonction publique' },
  { value: 'agent_etat', label: 'Agent de l\'État' },
  { value: 'agent_collectivite', label: 'Agent des collectivités territoriales' },
  { value: 'agent_hospitalier', label: 'Agent hospitalier' },
  { value: 'agent_education', label: 'Agent de l\'éducation nationale' },
  { value: 'atsem', label: 'ATSEM (Agent territorial spécialisé)' },
  { value: 'agent_entretien', label: 'Agent d\'entretien' },
  { value: 'agent_technique', label: 'Agent technique' },
  
  // Employés de la police et de l'armée
  { value: 'agent_police', label: 'Agent de police municipale' },
  { value: 'agent_securite', label: 'Agent de sécurité' },
  { value: 'agent_surveillance', label: 'Agent de surveillance' },
  { value: 'gardien', label: 'Gardien' },
  { value: 'surveillant', label: 'Surveillant' },
  { value: 'vigile', label: 'Vigile' },
  { value: 'agent_prevention', label: 'Agent de prévention' },
  
  // Employés des services directs aux particuliers
  { value: 'employe_service_direct', label: 'Employé des services directs aux particuliers' },
  { value: 'aide_menagere', label: 'Aide à domicile, aide ménagère' },
  { value: 'aide_domicile', label: 'Aide à domicile' },
  { value: 'assistant_maternel', label: 'Assistant maternel' },
  { value: 'auxiliaire_vie', label: 'Auxiliaire de vie' },
  { value: 'aide_soignant', label: 'Aide-soignant' },
  { value: 'auxiliaire_puericulture', label: 'Auxiliaire de puériculture' },
  { value: 'employe_hotel_restaurant', label: 'Employé d\'hôtel, restaurant' },
  { value: 'serveur', label: 'Serveur' },
  { value: 'barman', label: 'Barman, barmaid' },
  { value: 'employe_hotel', label: 'Employé d\'hôtel' },
  { value: 'receptionniste', label: 'Réceptionniste' },
  { value: 'femme_chambre', label: 'Femme de chambre' },
  { value: 'valet_parking', label: 'Valet de parking' },
  { value: 'bagagiste', label: 'Bagagiste' },
  { value: 'coiffeur_esthetiste', label: 'Coiffeur, esthéticien' },
  { value: 'coiffeur', label: 'Coiffeur' },
  { value: 'coiffeuse', label: 'Coiffeuse' },
  { value: 'esthetiste', label: 'Esthéticien' },
  { value: 'manucure', label: 'Manucure' },
  { value: 'masseur', label: 'Masseur bien-être' },
  { value: 'employe_funeraire', label: 'Employé funéraire' },
  { value: 'croque_mort', label: 'Croque-mort' },
  { value: 'employe_securite', label: 'Agent de sécurité, surveillant' },
  
  // ============================================
  // GROUPE 6 : OUVRIERS
  // ============================================
  // Ouvriers qualifiés de type industriel
  { value: 'ouvrier_qualifie_industrie', label: 'Ouvrier qualifié de l\'industrie' },
  { value: 'ouvrier_qualifie_mecanique', label: 'Ouvrier qualifié mécanique' },
  { value: 'ouvrier_qualifie_electricite', label: 'Ouvrier qualifié électricité' },
  { value: 'ouvrier_qualifie_electronique', label: 'Ouvrier qualifié électronique' },
  { value: 'ouvrier_qualifie_chimie', label: 'Ouvrier qualifié chimie' },
  { value: 'ouvrier_qualifie_plastique', label: 'Ouvrier qualifié plastique' },
  { value: 'ouvrier_qualifie_textile', label: 'Ouvrier qualifié textile' },
  { value: 'ouvrier_qualifie_alimentaire', label: 'Ouvrier qualifié alimentaire' },
  { value: 'ouvrier_qualifie_imprimerie', label: 'Ouvrier qualifié imprimerie' },
  { value: 'ouvrier_qualifie_bois', label: 'Ouvrier qualifié bois' },
  { value: 'ouvrier_qualifie_metallurgie', label: 'Ouvrier qualifié métallurgie' },
  { value: 'soudeur', label: 'Soudeur' },
  { value: 'chaudronnier', label: 'Chaudronnier' },
  { value: 'ajusteur', label: 'Ajusteur' },
  { value: 'tourneur', label: 'Tourneur' },
  { value: 'fraiseur', label: 'Fraiseur' },
  { value: 'mecanicien_industrie', label: 'Mécanicien industriel' },
  { value: 'electricien_industrie', label: 'Électricien industriel' },
  
  // Ouvriers qualifiés du bâtiment et des travaux publics
  { value: 'ouvrier_qualifie_batiment', label: 'Ouvrier qualifié du bâtiment' },
  { value: 'macon', label: 'Maçon' },
  { value: 'carreleur', label: 'Carreleur' },
  { value: 'plombier', label: 'Plombier' },
  { value: 'plombier_zingueur', label: 'Plombier-zingueur' },
  { value: 'electricien', label: 'Électricien' },
  { value: 'electricien_batiment', label: 'Électricien bâtiment' },
  { value: 'charpentier', label: 'Charpentier' },
  { value: 'menuisier', label: 'Menuisier' },
  { value: 'ebeniste', label: 'Ébéniste' },
  { value: 'serrurier', label: 'Serrurier' },
  { value: 'ferronnier', label: 'Ferronnier' },
  { value: 'couvreur', label: 'Couvreur' },
  { value: 'zinguier', label: 'Zingueur' },
  { value: 'peintre_batiment', label: 'Peintre en bâtiment' },
  { value: 'platrier', label: 'Plâtrier' },
  { value: 'carreleur_faiciencier', label: 'Carreleur-faïencier' },
  { value: 'solier_moquettiste', label: 'Solier-moquettiste' },
  { value: 'vitrier', label: 'Vitrier' },
  { value: 'miroitier', label: 'Miroitier' },
  { value: 'ouvrier_qualifie_tp', label: 'Ouvrier qualifié travaux publics' },
  { value: 'conducteur_engin', label: 'Conducteur d\'engin' },
  { value: 'conducteur_pelle', label: 'Conducteur de pelle mécanique' },
  { value: 'conducteur_niveleuse', label: 'Conducteur de niveleuse' },
  { value: 'ouvrier_route', label: 'Ouvrier de la route' },
  { value: 'ouvrier_terrassement', label: 'Ouvrier terrassement' },
  
  // Ouvriers qualifiés de type artisanal
  { value: 'ouvrier_qualifie_artisanat', label: 'Ouvrier qualifié de l\'artisanat' },
  { value: 'boucher', label: 'Boucher' },
  { value: 'charcutier', label: 'Charcutier' },
  { value: 'boulanger', label: 'Boulanger' },
  { value: 'patissier', label: 'Pâtissier' },
  { value: 'chocolatier', label: 'Chocolatier' },
  { value: 'confiseur', label: 'Confiseur' },
  { value: 'poissonnier', label: 'Poissonnier' },
  { value: 'fromager', label: 'Fromager' },
  { value: 'cordonnier', label: 'Cordonnier' },
  { value: 'maroquinier', label: 'Maroquinier' },
  { value: 'sellier', label: 'Sellier' },
  { value: 'tapissier', label: 'Tapissier' },
  { value: 'relieur', label: 'Relieur' },
  { value: 'graveur', label: 'Graveur' },
  { value: 'horloger', label: 'Horloger' },
  { value: 'bijoutier', label: 'Bijoutier' },
  { value: 'joaillier', label: 'Joaillier' },
  { value: 'orfevre', label: 'Orfèvre' },
  { value: 'verrier', label: 'Verrier' },
  { value: 'ceramiste', label: 'Céramiste' },
  { value: 'potier', label: 'Potier' },
  
  // Chauffeurs et ouvriers qualifiés de la manutention
  { value: 'chauffeur', label: 'Chauffeur' },
  { value: 'chauffeur_livreur', label: 'Chauffeur-livreur' },
  { value: 'chauffeur_poids_lourd', label: 'Chauffeur poids lourd' },
  { value: 'chauffeur_semi_remorque', label: 'Chauffeur semi-remorque' },
  { value: 'chauffeur_bus', label: 'Chauffeur de bus' },
  { value: 'chauffeur_car', label: 'Chauffeur de car' },
  { value: 'chauffeur_taxi', label: 'Chauffeur de taxi' },
  { value: 'chauffeur_vtc', label: 'Chauffeur VTC' },
  { value: 'chauffeur_ambulance', label: 'Chauffeur d\'ambulance' },
  { value: 'conducteur_train', label: 'Conducteur de train' },
  { value: 'conducteur_metro', label: 'Conducteur de métro' },
  { value: 'conducteur_tramway', label: 'Conducteur de tramway' },
  { value: 'manutentionnaire', label: 'Manutentionnaire' },
  { value: 'cariste', label: 'Cariste' },
  { value: 'magasinier', label: 'Magasinier' },
  { value: 'preparateur_commande', label: 'Préparateur de commande' },
  { value: 'gerant_stock', label: 'Gérant de stock' },
  
  // Ouvriers non qualifiés de type industriel
  { value: 'ouvrier_non_qualifie_industrie', label: 'Ouvrier non qualifié de l\'industrie' },
  { value: 'ouvrier_production', label: 'Ouvrier de production' },
  { value: 'ouvrier_assemblage', label: 'Ouvrier d\'assemblage' },
  { value: 'ouvrier_conditionnement', label: 'Ouvrier de conditionnement' },
  { value: 'ouvrier_emballage', label: 'Ouvrier d\'emballage' },
  { value: 'ouvrier_manutention', label: 'Ouvrier de manutention' },
  { value: 'ouvrier_entretien', label: 'Ouvrier d\'entretien' },
  { value: 'ouvrier_nettoyage', label: 'Ouvrier de nettoyage industriel' },
  
  // Ouvriers non qualifiés du bâtiment et des travaux publics
  { value: 'ouvrier_non_qualifie_batiment', label: 'Ouvrier non qualifié du bâtiment' },
  { value: 'manoeuvre_batiment', label: 'Manœuvre du bâtiment' },
  { value: 'aide_macon', label: 'Aide-maçon' },
  { value: 'aide_plombier', label: 'Aide-plombier' },
  { value: 'aide_electricien', label: 'Aide-électricien' },
  { value: 'aide_peintre', label: 'Aide-peintre' },
  { value: 'ouvrier_tp', label: 'Ouvrier travaux publics' },
  { value: 'manoeuvre_tp', label: 'Manœuvre travaux publics' },
  
  // Ouvriers non qualifiés de type artisanal
  { value: 'ouvrier_non_qualifie_artisanat', label: 'Ouvrier non qualifié de l\'artisanat' },
  { value: 'aide_boucher', label: 'Aide-boucher' },
  { value: 'aide_boulanger', label: 'Aide-boulanger' },
  { value: 'aide_patissier', label: 'Aide-pâtissier' },
  { value: 'aide_coiffeur', label: 'Aide-coiffeur' },
  
  // Ouvriers agricoles
  { value: 'ouvrier_agricole', label: 'Ouvrier agricole' },
  { value: 'ouvrier_viticole', label: 'Ouvrier viticole' },
  { value: 'ouvrier_maraicher', label: 'Ouvrier maraîcher' },
  { value: 'ouvrier_arboricole', label: 'Ouvrier arboricole' },
  { value: 'ouvrier_elevage', label: 'Ouvrier d\'élevage' },
  { value: 'ouvrier_peche', label: 'Ouvrier de la pêche' },
  { value: 'matelot', label: 'Matelot' },
  { value: 'mousse', label: 'Mousse' },
  
  // Manœuvres
  { value: 'manoeuvre', label: 'Manœuvre' },
  { value: 'manoeuvre_industrie', label: 'Manœuvre industrie' },
  { value: 'manoeuvre_batiment', label: 'Manœuvre bâtiment' },
  { value: 'manoeuvre_manutention', label: 'Manœuvre manutention' },
  { value: 'manoeuvre_nettoyage', label: 'Manœuvre nettoyage' },
  
  // ============================================
  // GROUPE 7 : RETRAITÉS
  // ============================================
  { value: 'retraite_agriculteur', label: 'Retraité agriculteur exploitant' },
  { value: 'retraite_artisan_commercant', label: 'Retraité artisan, commerçant, chef d\'entreprise' },
  { value: 'retraite_cadre', label: 'Retraité cadre' },
  { value: 'retraite_prof_intermediaire', label: 'Retraité profession intermédiaire' },
  { value: 'retraite_employe', label: 'Retraité employé' },
  { value: 'retraite_ouvrier', label: 'Retraité ouvrier' },
  { value: 'retraite_fonction_publique', label: 'Retraité de la fonction publique' },
  { value: 'retraite_armee', label: 'Retraité de l\'armée' },
  
  // ============================================
  // GROUPE 8 : AUTRES PERSONNES SANS ACTIVITÉ PROFESSIONNELLE
  // ============================================
  { value: 'chomeur', label: 'Chômeur (n\'ayant jamais travaillé)' },
  { value: 'chomeur_ancien_travailleur', label: 'Chômeur (ancien travailleur)' },
  { value: 'chomeur_indemnise', label: 'Chômeur indemnisé' },
  { value: 'chomeur_non_indemnise', label: 'Chômeur non indemnisé' },
  { value: 'etudiant', label: 'Étudiant' },
  { value: 'etudiant_universite', label: 'Étudiant université' },
  { value: 'etudiant_grande_ecole', label: 'Étudiant grande école' },
  { value: 'etudiant_lycee', label: 'Étudiant lycée' },
  { value: 'lyceen', label: 'Lycéen, collégien' },
  { value: 'collegien', label: 'Collégien' },
  { value: 'eleve_primaire', label: 'Élève primaire' },
  { value: 'apprenti', label: 'Apprenti' },
  { value: 'stagiaire', label: 'Stagiaire' },
  { value: 'militaire_du_contingent', label: 'Militaire du contingent' },
  { value: 'service_civique', label: 'Service civique' },
  { value: 'femme_au_foyer', label: 'Femme au foyer, homme au foyer' },
  { value: 'homme_au_foyer', label: 'Homme au foyer' },
  { value: 'personne_handicapee', label: 'Personne handicapée' },
  { value: 'personne_retraite_anticipée', label: 'Personne en retraite anticipée' },
  { value: 'personne_maladie_longue', label: 'Personne en arrêt maladie longue durée' },
  { value: 'autre_inactif', label: 'Autre personne inactive' },
  { value: 'autre', label: 'Autre' },
  
  // ============================================
  // NOMENCLATURE CSP POUR ÉLUS ET CANDIDATURES (64 rubriques)
  // ============================================
  // Professions agricoles
  { value: 'agriculteur_proprietaire_exploitant', label: 'Agriculteur-propriétaire exploitant' },
  { value: 'salarie_agricole', label: 'Salarié agricole' },
  
  // Marins
  { value: 'marin_patron', label: 'Marin (patron)' },
  { value: 'marin_salarie', label: 'Marin (salarié)' },
  
  // Professions industrielles et commerciales
  { value: 'industriel_chef_entreprise', label: 'Industriel-chef d\'entreprise' },
  { value: 'administrateur_societe_industrielle', label: 'Administrateur de société industrielle' },
  { value: 'agent_affaire', label: 'Agent d\'affaires' },
  { value: 'entrepreneur_batiment', label: 'Entrepreneur en bâtiment' },
  { value: 'proprietaire', label: 'Propriétaire' },
  
  // Ingénieurs et techniciens
  { value: 'ingenieur_salarie', label: 'Ingénieur salarié' },
  { value: 'agent_technique_technicien_prive', label: 'Agent technique et technicien du privé' },
  { value: 'representant_commerce', label: 'Représentant de commerce' },
  { value: 'agent_assurance', label: 'Agent d\'assurance' },
  
  // Cadres et employés privés
  { value: 'cadre_superieur_prive', label: 'Cadre supérieur (privé)' },
  { value: 'autre_cadre_prive', label: 'Autre cadre (privé)' },
  { value: 'employe_secteur_prive', label: 'Employé (secteur privé)' },
  { value: 'ouvrier_prive', label: 'Ouvrier (privé)' },
  
  // Professions sociales et médicales
  { value: 'assistante_sociale', label: 'Assistante sociale' },
  { value: 'salarie_secteur_medical', label: 'Salarié du secteur médical' },
  
  // Professions libérales médicales
  { value: 'chirurgien', label: 'Chirurgien' },
  { value: 'dentiste', label: 'Dentiste' },
  
  // Professions libérales juridiques
  { value: 'conseiller_juridique', label: 'Conseiller juridique' },
  { value: 'agent_general_assurance', label: 'Agent général d\'assurance' },
  
  // Autres professions libérales
  { value: 'ingenieur_conseil', label: 'Ingénieur conseil' },
  { value: 'journaliste_autre_media', label: 'Journaliste et autre média' },
  { value: 'homme_lettre_artiste', label: 'Homme de lettres et artiste' },
  { value: 'autre_profession_liberale', label: 'Autre profession libérale' },
  
  // Professions de l'enseignement
  { value: 'professeur_faculte', label: 'Professeur de faculté' },
  { value: 'professeur_secondaire_technique', label: 'Professeur du secondaire et technique' },
  { value: 'enseignant_1er_degre_directeur_ecole', label: 'Enseignant 1er degré-directeur d\'école' },
  { value: 'profession_rattachee_enseignement', label: 'Profession rattachée à l\'enseignement' },
  
  // Fonction publique
  { value: 'grand_corps_etat', label: 'Grand corps de l\'État (moins les enseignants)' },
  { value: 'fonctionnaire_categorie_a', label: 'Fonctionnaire catégorie A' },
  { value: 'fonctionnaire_categorie_b', label: 'Fonctionnaire catégorie B' },
  { value: 'fonctionnaire_categorie_c', label: 'Fonctionnaire catégorie C' },
  
  // Entreprises publiques
  { value: 'cadre_superieur_entreprise_publique', label: 'Cadre supérieur (entreprises publiques)' },
  { value: 'cadre_entreprise_publique', label: 'Cadre (entreprises publiques)' },
  { value: 'employe_entreprise_publique', label: 'Employé (autres entreprises publiques)' },
  { value: 'agent_subalterne_entreprise_publique', label: 'Agent subalterne (entreprises publiques)' },
  
  // Autres professions
  { value: 'permanent_politique', label: 'Permanent politique' },
  { value: 'ministre_culte', label: 'Ministre du culte' },
  { value: 'autre_profession', label: 'Autre profession' },
  { value: 'sans_profession_declaree', label: 'Sans profession déclarée' },
  
  // Retraités
  { value: 'retraite_agricole', label: 'Retraité agricole' },
  { value: 'retraite_artisan_commercant_chef_entreprise', label: 'Retraité artisan, commerçant et chef d\'entreprise' },
  { value: 'retraite_profession_liberale', label: 'Retraité des professions libérales' },
  { value: 'retraite_salarie_prive', label: 'Retraité salarié privé' },
  { value: 'retraite_enseignement', label: 'Retraité de l\'enseignement' },
  { value: 'retraite_fonction_publique', label: 'Retraité de la fonction publique (moins l\'enseignement)' },
  { value: 'retraite_entreprise_publique', label: 'Retraité des entreprises publiques' },
];

